name: Uptime Ping

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Hit health endpoint
        env:
          HEALTHCHECK_URL: ${{ secrets.RENDER_HEALTHCHECK_URL }}
        run: |
          if [ -z "$HEALTHCHECK_URL" ]; then
            echo "HEALTHCHECK_URL not set. Configure RENDER_HEALTHCHECK_URL secret." >&2
            exit 1
          fi
          curl --fail --silent --show-error "$HEALTHCHECK_URL" || exit 1
